pep8:
  disable:
    - E305
    - E306
    - E115
    - E501
    - E722

pycodestyle:
  disable:
    - E115
    - E305
    - E306
    - E501
    - E722

pyflakes:
  disable:
    - F821
    - F841

pylint:
  disable:
    - bare-except
    - consider-using-f-string
    - django-not-configured
    - import-error
    - import-outside-toplevel
    - line-too-long
    - logging-format-interpolation
    - method-hidden
    - multiple-imports
    - super-with-arguments
    - too-many-arguments
    - undefined-variable
    - unused-argument
    - unused-variable
    - unspecified-encoding
    - useless-object-inheritance
    - useless-suppression
